package wallet

import (
	"os"
	"strings"
	"testing"
)

func walletSchema(t *testing.T) string {
	t.Helper()
	source, err := os.ReadFile("../../WALLET_LEDGER_SCHEMA.sql")
	if err != nil {
		t.Fatal(err)
	}
	return string(source)
}

func TestSchemaDefinesRequiredTables(t *testing.T) {
	source := walletSchema(t)
	required := []string{
		"CREATE TABLE IF NOT EXISTS public.wallet_accounts",
		"CREATE TABLE IF NOT EXISTS public.wallet_transactions",
		"CREATE TABLE IF NOT EXISTS public.wallet_ledger_entries",
		"CREATE TABLE IF NOT EXISTS public.payment_intents",
		"CREATE TABLE IF NOT EXISTS public.provider_events",
		"CREATE TABLE IF NOT EXISTS public.withdrawal_requests",
		"CREATE TABLE IF NOT EXISTS public.wallet_authorizations",
		"CREATE TABLE IF NOT EXISTS public.wallet_authorization_events",
		"CREATE TABLE IF NOT EXISTS public.settlement_records",
		"CREATE TABLE IF NOT EXISTS public.reconciliation_runs",
		"CREATE TABLE IF NOT EXISTS public.financial_jobs",
		"CREATE TABLE IF NOT EXISTS public.financial_metrics",
		"CREATE TABLE IF NOT EXISTS public.provider_statement_imports",
		"CREATE TABLE IF NOT EXISTS public.provider_statement_lines",
		"CREATE TABLE IF NOT EXISTS public.refund_intents",
		"CREATE TABLE IF NOT EXISTS public.chargeback_records",
		"CREATE TABLE IF NOT EXISTS public.financial_disputes",
		"CREATE TABLE IF NOT EXISTS public.financial_incidents",
		"CREATE TABLE IF NOT EXISTS public.financial_runbooks",
		"CREATE TABLE IF NOT EXISTS public.provider_certifications",
		"CREATE TABLE IF NOT EXISTS public.provider_certification_checks",
		"CREATE TABLE IF NOT EXISTS public.recovery_drills",
		"CREATE TABLE IF NOT EXISTS public.recovery_drill_events",
		"CREATE TABLE IF NOT EXISTS public.recovery_scorecards",
		"CREATE TABLE IF NOT EXISTS public.finance_approval_requests",
		"CREATE TABLE IF NOT EXISTS public.finance_approval_events",
		"CREATE TABLE IF NOT EXISTS public.launch_gates",
		"CREATE TABLE IF NOT EXISTS public.finance_close_runs",
		"CREATE TABLE IF NOT EXISTS public.finance_signoffs",
		"CREATE TABLE IF NOT EXISTS public.launch_readiness_scorecards",
		"CREATE TABLE IF NOT EXISTS public.release_readiness_evidence",
		"CREATE TABLE IF NOT EXISTS public.launch_gate_drills",
		"CREATE TABLE IF NOT EXISTS public.final_readiness_scorecards",
		"CREATE TABLE IF NOT EXISTS public.executive_signoff_packets",
		"CREATE TABLE IF NOT EXISTS public.executive_approval_records",
		"CREATE TABLE IF NOT EXISTS public.launch_blockers",
		"CREATE TABLE IF NOT EXISTS public.internal_launch_decisions",
		"CREATE TABLE IF NOT EXISTS public.live_drill_evidence",
		"CREATE TABLE IF NOT EXISTS public.drill_evidence_reviews",
		"CREATE TABLE IF NOT EXISTS public.production_exceptions",
		"CREATE TABLE IF NOT EXISTS public.reliability_scorecards",
		"CREATE TABLE IF NOT EXISTS public.control_room_snapshots",
		"CREATE TABLE IF NOT EXISTS public.daily_finance_closes",
		"CREATE TABLE IF NOT EXISTS public.daily_close_reviews",
		"CREATE TABLE IF NOT EXISTS public.daily_reliability_metrics",
		"CREATE TABLE IF NOT EXISTS public.pilot_monitoring_snapshots",
		"CREATE TABLE IF NOT EXISTS public.internal_pilot_runbooks",
		"CREATE TABLE IF NOT EXISTS public.day1_close_simulations",
		"CREATE TABLE IF NOT EXISTS public.incident_escalations",
		"CREATE TABLE IF NOT EXISTS public.pilot_operations_timeline",
		"CREATE TABLE IF NOT EXISTS public.internal_pilot_success_criteria",
		"CREATE TABLE IF NOT EXISTS public.pilot_authorizations",
		"CREATE TABLE IF NOT EXISTS public.pilot_scope_definitions",
		"CREATE TABLE IF NOT EXISTS public.pilot_success_definitions",
		"CREATE TABLE IF NOT EXISTS public.internal_pilot_authorization_executions",
		"CREATE TABLE IF NOT EXISTS public.internal_pilot_authorization_audits",
		"CREATE TABLE IF NOT EXISTS public.internal_pilot_participants",
		"CREATE TABLE IF NOT EXISTS public.internal_pilot_participant_events",
		"CREATE TABLE IF NOT EXISTS public.internal_pilot_health_reports",
		"CREATE TABLE IF NOT EXISTS public.internal_pilot_incidents",
		"CREATE TABLE IF NOT EXISTS public.internal_pilot_kill_switches",
		"CREATE TABLE IF NOT EXISTS public.internal_pilot_kill_switch_events",
		"CREATE TABLE IF NOT EXISTS public.internal_pilot_execution_events",
		"CREATE TABLE IF NOT EXISTS public.internal_pilot_evidence_packages",
		"CREATE TABLE IF NOT EXISTS public.internal_pilot_objective_results",
		"CREATE TABLE IF NOT EXISTS public.internal_pilot_board_reviews",
		"CREATE TABLE IF NOT EXISTS public.internal_pilot_review_findings",
		"CREATE TABLE IF NOT EXISTS public.internal_pilot_readiness_assessments",
		"CREATE TABLE IF NOT EXISTS public.wallet_pilot_programs",
		"CREATE TABLE IF NOT EXISTS public.wallet_pilot_participants",
		"CREATE TABLE IF NOT EXISTS public.wallet_pilot_transactions",
		"CREATE TABLE IF NOT EXISTS public.wallet_pilot_reconciliation_reports",
		"CREATE TABLE IF NOT EXISTS public.wallet_pilot_fraud_events",
		"CREATE TABLE IF NOT EXISTS public.wallet_pilot_kill_switches",
		"CREATE TABLE IF NOT EXISTS public.pilot_wallet_groups",
		"CREATE TABLE IF NOT EXISTS public.pilot_wallet_users",
		"CREATE TABLE IF NOT EXISTS public.pilot_wallet_user_events",
	}
	for _, pattern := range required {
		if !strings.Contains(source, pattern) {
			t.Fatalf("schema missing %s", pattern)
		}
	}
}

func TestSchemaConstraintsAndImmutability(t *testing.T) {
	source := walletSchema(t)
	required := []string{
		"idempotency_key text NOT NULL UNIQUE",
		"CHECK (amount > 0)",
		"CHECK (total_amount > 0)",
		"CHECK (entry_type IN ('debit', 'credit'))",
		"CHECK (currency IN ('USD', 'ZWG'))",
		"'cash_platform_fee'",
		"'wallet_settlement'",
		"'onemoney'",
		"'ecocash'",
		"'innbucks'",
		"'card'",
		"'pending_provider_payment'",
		"'completed'",
		"'authorized'",
		"'captured'",
		"'voided'",
		"'refunded'",
		"'released'",
		"'expired'",
		"'processing'",
		"'settled'",
		"'liability_recorded'",
		"'pilot_rider'",
		"'pilot_driver'",
		"'pilot_admin'",
		"'enabled'",
		"'suspended'",
		"'removed'",
		"UNIQUE (provider, provider_event_id)",
		"WHERE provider_reference IS NOT NULL",
		"UNIQUE (user_id, provider, operation, idempotency_key)",
		"amount_minor bigint",
		"'cash_settlement'",
		"'wallet_capture'",
		"'authorization_release'",
		"'authorization_expiration'",
		"'reconciliation_run'",
		"'provider_callback_processing'",
		"'refund_processing'",
		"'chargeback_processing'",
		"'dispute_resolution'",
		"'provider_statement_reconciliation'",
		"'financial_incident_review'",
		"'provider_certification'",
		"'recovery_drill'",
		"'settlement_failure_drill'",
		"'reconciliation_failure_drill'",
		"'provider_callback_failure_drill'",
		"'dual_approval_review'",
		"'finance_close'",
		"'launch_gate_review'",
		"'release_readiness_review'",
		"'launch_gate_drill'",
		"'executive_signoff_packet'",
		"'internal_launch_drill'",
		"'drill_evidence_review'",
		"'production_exception_closure'",
		"'daily_finance_close'",
		"'internal_pilot_runbook'",
		"'internal_pilot_authorization'",
		"'amount_mismatch'",
		"'currency_mismatch'",
		"'missing_ledger'",
		"'unmatched_provider'",
		"'refund_failure'",
		"'chargeback_failure'",
		"'open_dispute'",
		"'financial_incident'",
		"'certification_failure'",
		"'recovery_drill_failure'",
		"'recovery_score'",
		"'launch_gate_blocked'",
		"'finance_close_failure'",
		"'release_readiness_score'",
		"'launch_gate_drill_failure'",
		"'launch_blocker_open'",
		"'production_exception_open'",
		"required_approval_count integer NOT NULL DEFAULT 2 CHECK (required_approval_count >= 2)",
		"UNIQUE (request_id, approver_id)",
		"'public_payment_activation'",
		"'provider_activation'",
		"'signed_off'",
		"'monthly'",
		"'finance_close'",
		"public_payments_ready boolean",
		"category text NOT NULL CHECK (category IN ('architecture', 'reliability', 'security', 'finance', 'governance', 'operations', 'provider_readiness', 'launch_readiness'))",
		"status text NOT NULL DEFAULT 'present' CHECK (status IN ('present', 'missing', 'warning'))",
		"missing_approval_blocked boolean NOT NULL DEFAULT false",
		"no_activation_mutation boolean NOT NULL DEFAULT true",
		"launch_recommendation text NOT NULL CHECK (launch_recommendation IN ('not_approved_for_public_launch', 'approved_for_controlled_internal_launch_drill_only'))",
		"packet_type text NOT NULL CHECK (packet_type IN ('finance', 'cto', 'risk', 'operations', 'executive_release'))",
		"status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected', 'conditional_approval'))",
		"approver_role text NOT NULL CHECK (approver_role IN ('finance', 'cto', 'risk', 'operations'))",
		"severity text NOT NULL CHECK (severity IN ('low', 'medium', 'high', 'critical'))",
		"outcome text NOT NULL CHECK (outcome IN ('not_ready', 'internal_pilot_ready', 'controlled_launch_ready', 'public_launch_ready'))",
		"drill_type text NOT NULL CHECK (drill_type IN ('settlement', 'authorization', 'reconciliation', 'provider_callback', 'refund', 'dispute', 'launch_gate'))",
		"reviewer_role text NOT NULL CHECK (reviewer_role IN ('finance', 'cto', 'risk', 'operations'))",
		"status text NOT NULL DEFAULT 'open' CHECK (status IN ('open', 'investigating', 'mitigated', 'verified', 'closed'))",
		"authorization_outcome text NOT NULL CHECK (authorization_outcome IN ('not_ready', 'ready_for_internal_pilot', 'ready_for_controlled_launch', 'ready_for_public_launch'))",
		"settlement_health text NOT NULL CHECK (settlement_health IN ('green', 'yellow', 'red'))",
		"status text NOT NULL DEFAULT 'open' CHECK (status IN ('open', 'reconciling', 'pending_review', 'signed_off', 'failed'))",
		"review_role text NOT NULL CHECK (review_role IN ('finance', 'operations'))",
		"settlement_success_rate integer NOT NULL CHECK (settlement_success_rate >= 0 AND settlement_success_rate <= 100)",
		"pilot_users integer NOT NULL DEFAULT 0 CHECK (pilot_users >= 0)",
		"runbook_type text NOT NULL CHECK (runbook_type IN ('settlement_incident', 'reconciliation_incident', 'provider_callback_failure', 'refund_incident', 'dispute_incident', 'authorization_failure'))",
		"level text NOT NULL CHECK (level IN ('informational', 'warning', 'high', 'critical'))",
		"event_type text NOT NULL CHECK (event_type IN ('pilot_start', 'pilot_checkpoint', 'pilot_review', 'pilot_close'))",
		"settlement_success boolean NOT NULL DEFAULT false",
		"decision text NOT NULL CHECK (decision IN ('no_go', 'conditional_go', 'go'))",
		"critical_exceptions_exist boolean NOT NULL DEFAULT false",
		"finance_signoff_missing boolean NOT NULL DEFAULT false",
		"pilot_duration_days integer NOT NULL CHECK (pilot_duration_days > 0)",
		"settlement_reliability_target integer NOT NULL CHECK (settlement_reliability_target >= 0 AND settlement_reliability_target <= 100)",
		"status text NOT NULL CHECK (status IN ('active', 'expired', 'revoked', 'completed'))",
		"decision text NOT NULL CHECK (decision IN ('approved', 'conditional_approval', 'rejected', 'expired'))",
		"readiness_score_threshold integer NOT NULL CHECK (readiness_score_threshold >= 0 AND readiness_score_threshold <= 100)",
		"authorization_execution_id uuid NOT NULL REFERENCES public.internal_pilot_authorization_executions(id)",
		"role text NOT NULL CHECK (role IN ('rider', 'driver', 'admin', 'operations', 'finance', 'risk'))",
		"status text NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'suspended', 'removed'))",
		"UNIQUE (authorization_execution_id, user_id, role)",
		"ride_completion_rate integer NOT NULL DEFAULT 0 CHECK (ride_completion_rate >= 0 AND ride_completion_rate <= 100)",
		"severity text NOT NULL CHECK (severity IN ('low', 'medium', 'high', 'critical'))",
		"status text NOT NULL DEFAULT 'open' CHECK (status IN ('open', 'investigating', 'mitigated', 'resolved', 'closed'))",
		"service text NOT NULL UNIQUE CHECK (service IN ('ride_requests', 'matching', 'dispatch', 'wallets', 'deposits', 'withdrawals', 'settlements'))",
		"event_type text NOT NULL CHECK (event_type IN (",
		"'participant_joined'",
		"'ride_requested'",
		"'wallet_payment_completed'",
		"'authorization_check_failed'",
		"'kill_switch_triggered'",
		"report_period_end > report_period_start",
		"compliance_score integer NOT NULL DEFAULT 0 CHECK (compliance_score >= 0 AND compliance_score <= 100)",
		"objective_name text NOT NULL",
		"achieved boolean NOT NULL DEFAULT false",
		"review_status text NOT NULL DEFAULT 'pending' CHECK (review_status IN ('pending', 'in_review', 'completed'))",
		"decision text NOT NULL DEFAULT 'defer' CHECK (decision IN ('approved', 'conditional_approval', 'rejected', 'defer'))",
		"category text NOT NULL CHECK (category IN ('operations', 'financial', 'compliance', 'platform', 'safety', 'dispatch', 'wallet', 'governance'))",
		"category text NOT NULL CHECK (category IN ('operational_readiness', 'financial_readiness', 'dispatch_readiness', 'wallet_readiness', 'governance_readiness', 'compliance_readiness', 'scalability_readiness'))",
		"score integer NOT NULL CHECK (score >= 0 AND score <= 100)",
		"target_score integer NOT NULL CHECK (target_score >= 0 AND target_score <= 100)",
		"city text NOT NULL CHECK (city IN ('Gwanda', 'Bulawayo'))",
		"status text NOT NULL DEFAULT 'planned' CHECK (status IN ('planned', 'active', 'paused', 'completed', 'suspended'))",
		"wallet_balance_limit_minor bigint NOT NULL CHECK (wallet_balance_limit_minor >= 0)",
		"daily_transaction_limit_minor bigint NOT NULL CHECK (daily_transaction_limit_minor >= 0)",
		"monthly_transaction_limit_minor bigint NOT NULL CHECK (monthly_transaction_limit_minor >= 0)",
		"participant_type text NOT NULL CHECK (participant_type IN ('rider', 'driver'))",
		"UNIQUE (program_id, user_id, participant_type)",
		"transaction_type text NOT NULL CHECK (transaction_type IN ('deposit', 'ride_payment', 'refund', 'adjustment'))",
		"amount_minor bigint NOT NULL CHECK (amount_minor > 0)",
		"status text NOT NULL DEFAULT 'recorded' CHECK (status IN ('recorded', 'rejected', 'failed'))",
		"status text NOT NULL CHECK (status IN ('balanced', 'variance_detected', 'investigating'))",
		"event_type text NOT NULL CHECK (event_type IN ('duplicate_payments', 'unusual_payment_frequency', 'abnormal_refund_activity', 'rapid_balance_cycling', 'multi_account_abuse', 'wallet_farming', 'pilot_abuse', 'reconciliation_variance'))",
		"control text NOT NULL CHECK (control IN ('disable_deposits', 'disable_wallet_payments', 'disable_refunds', 'disable_wallet_adjustments'))",
		"UNIQUE (program_id, control)",
		"idx_internal_pilot_participants_auth_status",
		"idx_internal_pilot_participants_user",
		"idx_internal_pilot_health_reports_date",
		"idx_internal_pilot_incidents_status",
		"idx_internal_pilot_kill_switches_status",
		"idx_internal_pilot_execution_events_auth_type",
		"idx_internal_pilot_execution_events_entity",
		"idx_internal_pilot_evidence_packages_period",
		"idx_internal_pilot_objective_results_auth",
		"idx_internal_pilot_board_reviews_auth_status",
		"idx_internal_pilot_review_findings_review_severity",
		"idx_internal_pilot_readiness_assessments_review_category",
		"idx_wallet_pilot_programs_city_status",
		"idx_wallet_pilot_participants_program_status",
		"idx_wallet_pilot_transactions_program_type",
		"idx_wallet_pilot_reconciliation_reports_program_date",
		"idx_wallet_pilot_fraud_events_program_severity",
		"idx_wallet_pilot_kill_switches_program_control",
		"'signature_verification'",
		"'callback_replay_window'",
		"'processor_authorize_capture'",
		"'provider_callback_failure'",
		"'provider_statement_mismatch'",
		"'green'",
		"'yellow'",
		"'red'",
		"'pending_review'",
		"'chargeback'",
		"'under_review'",
		"'resolved_refund'",
		"'critical'",
		"'settlement_failure'",
		"'failed_capture'",
		"'failed_release'",
		"statement_reference text NOT NULL",
		"line_reference text NOT NULL",
		"matched_wallet_transaction_id uuid",
		"matched_payment_intent_id uuid",
		"prevent_wallet_ledger_entry_mutation",
		"BEFORE UPDATE ON public.wallet_ledger_entries",
		"BEFORE DELETE ON public.wallet_ledger_entries",
	}
	for _, pattern := range required {
		if !strings.Contains(source, pattern) {
			t.Fatalf("schema missing constraint/immutability pattern %s", pattern)
		}
	}
}

func TestSchemaRLSPolicies(t *testing.T) {
	source := walletSchema(t)
	required := []string{
		"ALTER TABLE public.wallet_accounts ENABLE ROW LEVEL SECURITY",
		"ALTER TABLE public.wallet_transactions ENABLE ROW LEVEL SECURITY",
		"ALTER TABLE public.wallet_ledger_entries ENABLE ROW LEVEL SECURITY",
		"ALTER TABLE public.financial_jobs ENABLE ROW LEVEL SECURITY",
		"ALTER TABLE public.financial_metrics ENABLE ROW LEVEL SECURITY",
		"ALTER TABLE public.provider_statement_imports ENABLE ROW LEVEL SECURITY",
		"ALTER TABLE public.provider_statement_lines ENABLE ROW LEVEL SECURITY",
		"ALTER TABLE public.refund_intents ENABLE ROW LEVEL SECURITY",
		"ALTER TABLE public.chargeback_records ENABLE ROW LEVEL SECURITY",
		"ALTER TABLE public.financial_disputes ENABLE ROW LEVEL SECURITY",
		"ALTER TABLE public.financial_incidents ENABLE ROW LEVEL SECURITY",
		"ALTER TABLE public.financial_runbooks ENABLE ROW LEVEL SECURITY",
		"ALTER TABLE public.provider_certifications ENABLE ROW LEVEL SECURITY",
		"ALTER TABLE public.provider_certification_checks ENABLE ROW LEVEL SECURITY",
		"ALTER TABLE public.recovery_drills ENABLE ROW LEVEL SECURITY",
		"ALTER TABLE public.recovery_drill_events ENABLE ROW LEVEL SECURITY",
		"ALTER TABLE public.recovery_scorecards ENABLE ROW LEVEL SECURITY",
		"ALTER TABLE public.finance_approval_requests ENABLE ROW LEVEL SECURITY",
		"ALTER TABLE public.finance_approval_events ENABLE ROW LEVEL SECURITY",
		"ALTER TABLE public.launch_gates ENABLE ROW LEVEL SECURITY",
		"ALTER TABLE public.finance_close_runs ENABLE ROW LEVEL SECURITY",
		"ALTER TABLE public.finance_signoffs ENABLE ROW LEVEL SECURITY",
		"ALTER TABLE public.launch_readiness_scorecards ENABLE ROW LEVEL SECURITY",
		"ALTER TABLE public.release_readiness_evidence ENABLE ROW LEVEL SECURITY",
		"ALTER TABLE public.launch_gate_drills ENABLE ROW LEVEL SECURITY",
		"ALTER TABLE public.final_readiness_scorecards ENABLE ROW LEVEL SECURITY",
		"ALTER TABLE public.executive_signoff_packets ENABLE ROW LEVEL SECURITY",
		"ALTER TABLE public.executive_approval_records ENABLE ROW LEVEL SECURITY",
		"ALTER TABLE public.launch_blockers ENABLE ROW LEVEL SECURITY",
		"ALTER TABLE public.internal_launch_decisions ENABLE ROW LEVEL SECURITY",
		"ALTER TABLE public.live_drill_evidence ENABLE ROW LEVEL SECURITY",
		"ALTER TABLE public.drill_evidence_reviews ENABLE ROW LEVEL SECURITY",
		"ALTER TABLE public.production_exceptions ENABLE ROW LEVEL SECURITY",
		"ALTER TABLE public.reliability_scorecards ENABLE ROW LEVEL SECURITY",
		"ALTER TABLE public.control_room_snapshots ENABLE ROW LEVEL SECURITY",
		"ALTER TABLE public.daily_finance_closes ENABLE ROW LEVEL SECURITY",
		"ALTER TABLE public.daily_close_reviews ENABLE ROW LEVEL SECURITY",
		"ALTER TABLE public.daily_reliability_metrics ENABLE ROW LEVEL SECURITY",
		"ALTER TABLE public.pilot_monitoring_snapshots ENABLE ROW LEVEL SECURITY",
		"ALTER TABLE public.internal_pilot_runbooks ENABLE ROW LEVEL SECURITY",
		"ALTER TABLE public.day1_close_simulations ENABLE ROW LEVEL SECURITY",
		"ALTER TABLE public.incident_escalations ENABLE ROW LEVEL SECURITY",
		"ALTER TABLE public.pilot_operations_timeline ENABLE ROW LEVEL SECURITY",
		"ALTER TABLE public.internal_pilot_success_criteria ENABLE ROW LEVEL SECURITY",
		"ALTER TABLE public.pilot_authorizations ENABLE ROW LEVEL SECURITY",
		"ALTER TABLE public.pilot_scope_definitions ENABLE ROW LEVEL SECURITY",
		"ALTER TABLE public.pilot_success_definitions ENABLE ROW LEVEL SECURITY",
		"ALTER TABLE public.internal_pilot_authorization_executions ENABLE ROW LEVEL SECURITY",
		"ALTER TABLE public.internal_pilot_authorization_audits ENABLE ROW LEVEL SECURITY",
		"ALTER TABLE public.internal_pilot_participants ENABLE ROW LEVEL SECURITY",
		"ALTER TABLE public.internal_pilot_participant_events ENABLE ROW LEVEL SECURITY",
		"ALTER TABLE public.internal_pilot_health_reports ENABLE ROW LEVEL SECURITY",
		"ALTER TABLE public.internal_pilot_incidents ENABLE ROW LEVEL SECURITY",
		"ALTER TABLE public.internal_pilot_kill_switches ENABLE ROW LEVEL SECURITY",
		"ALTER TABLE public.internal_pilot_kill_switch_events ENABLE ROW LEVEL SECURITY",
		"ALTER TABLE public.internal_pilot_execution_events ENABLE ROW LEVEL SECURITY",
		"ALTER TABLE public.internal_pilot_evidence_packages ENABLE ROW LEVEL SECURITY",
		"ALTER TABLE public.internal_pilot_objective_results ENABLE ROW LEVEL SECURITY",
		"ALTER TABLE public.internal_pilot_board_reviews ENABLE ROW LEVEL SECURITY",
		"ALTER TABLE public.internal_pilot_review_findings ENABLE ROW LEVEL SECURITY",
		"ALTER TABLE public.internal_pilot_readiness_assessments ENABLE ROW LEVEL SECURITY",
		"ALTER TABLE public.wallet_pilot_programs ENABLE ROW LEVEL SECURITY",
		"ALTER TABLE public.wallet_pilot_participants ENABLE ROW LEVEL SECURITY",
		"ALTER TABLE public.wallet_pilot_transactions ENABLE ROW LEVEL SECURITY",
		"ALTER TABLE public.wallet_pilot_reconciliation_reports ENABLE ROW LEVEL SECURITY",
		"ALTER TABLE public.wallet_pilot_fraud_events ENABLE ROW LEVEL SECURITY",
		"ALTER TABLE public.wallet_pilot_kill_switches ENABLE ROW LEVEL SECURITY",
		"ALTER TABLE public.wallet_authorizations ENABLE ROW LEVEL SECURITY",
		"ALTER TABLE public.wallet_authorization_events ENABLE ROW LEVEL SECURITY",
		"ALTER TABLE public.pilot_wallet_groups ENABLE ROW LEVEL SECURITY",
		"ALTER TABLE public.pilot_wallet_users ENABLE ROW LEVEL SECURITY",
		"ALTER TABLE public.pilot_wallet_user_events ENABLE ROW LEVEL SECURITY",
		"wallet_accounts_owner_select",
		"wallet_transactions_owner_select",
		"wallet_ledger_entries_owner_select",
		"wallet_authorizations_owner_select",
		"wallet_authorization_events_owner_select",
		"financial_jobs_admin_select",
		"provider_statement_lines_admin_select",
		"refund_intents_admin_select",
		"chargeback_records_admin_select",
		"financial_disputes_admin_select",
		"financial_incidents_admin_select",
		"financial_runbooks_admin_select",
		"provider_certifications_admin_select",
		"provider_certification_checks_admin_select",
		"recovery_drills_admin_select",
		"recovery_drill_events_admin_select",
		"recovery_scorecards_admin_select",
		"finance_approval_requests_admin_select",
		"finance_approval_events_admin_select",
		"launch_gates_admin_select",
		"finance_close_runs_admin_select",
		"finance_signoffs_admin_select",
		"launch_readiness_scorecards_admin_select",
		"release_readiness_evidence_admin_select",
		"launch_gate_drills_admin_select",
		"final_readiness_scorecards_admin_select",
		"executive_signoff_packets_admin_select",
		"executive_approval_records_admin_select",
		"launch_blockers_admin_select",
		"internal_launch_decisions_admin_select",
		"live_drill_evidence_admin_select",
		"drill_evidence_reviews_admin_select",
		"production_exceptions_admin_select",
		"reliability_scorecards_admin_select",
		"control_room_snapshots_admin_select",
		"daily_finance_closes_admin_select",
		"daily_close_reviews_admin_select",
		"daily_reliability_metrics_admin_select",
		"pilot_monitoring_snapshots_admin_select",
		"internal_pilot_runbooks_admin_select",
		"day1_close_simulations_admin_select",
		"incident_escalations_admin_select",
		"pilot_operations_timeline_admin_select",
		"internal_pilot_success_criteria_admin_select",
		"pilot_authorizations_admin_select",
		"pilot_scope_definitions_admin_select",
		"pilot_success_definitions_admin_select",
		"internal_pilot_authorization_executions_admin_select",
		"internal_pilot_authorization_audits_admin_select",
		"internal_pilot_participants_admin_select",
		"internal_pilot_participant_events_admin_select",
		"internal_pilot_health_reports_admin_select",
		"internal_pilot_incidents_admin_select",
		"internal_pilot_kill_switches_admin_select",
		"internal_pilot_kill_switch_events_admin_select",
		"internal_pilot_execution_events_admin_select",
		"internal_pilot_evidence_packages_admin_select",
		"internal_pilot_objective_results_admin_select",
		"internal_pilot_board_reviews_admin_select",
		"internal_pilot_review_findings_admin_select",
		"internal_pilot_readiness_assessments_admin_select",
		"wallet_pilot_programs_admin_select",
		"wallet_pilot_participants_admin_select",
		"wallet_pilot_transactions_admin_select",
		"wallet_pilot_reconciliation_reports_admin_select",
		"wallet_pilot_fraud_events_admin_select",
		"wallet_pilot_kill_switches_admin_select",
		"pilot_wallet_users_admin_select",
		"pilot_wallet_user_events_admin_select",
		"auth.uid()",
		"app_metadata",
	}
	for _, pattern := range required {
		if !strings.Contains(source, pattern) {
			t.Fatalf("schema missing RLS pattern %s", pattern)
		}
	}
}

func TestSchemaDoesNotModifyRideTables(t *testing.T) {
	source := walletSchema(t)
	banned := []string{
		"ALTER TABLE public.rides",
		"ALTER TABLE public.ride_offers",
		"DROP TABLE public.rides",
		"DROP TABLE public.ride_offers",
	}
	for _, pattern := range banned {
		if strings.Contains(source, pattern) {
			t.Fatalf("schema must not modify V1 ride tables: %s", pattern)
		}
	}
}
